### ISSUE TITLE
Can't compile in g++ 8.3

### ISSUE THREAD

**Issue by jimcruse** [PacktPublishing/Cpp17-STL-Cookbook#10]
Can't compile files as downloaded with g++8.3 under Debian buster
First: experimental/ not found so I modified file to not look in experimental
And to use <filesystem> only
Please see attached script from build
See attached list.cpp as modified

**Comment by jimcruse** [comment]
[Build log file[]()

**Comment by sonam-packt** [comment]
Hello @jimcruse please refer https://github.com/PacktPublishing/Cpp17-STL-Cookbook . This contains all fixes and modernizations. If you are still not able to build, please check with your tools.

**Comment by jimcruse** [comment]
Chapter 10 build works now, if you manually create bin directory first

**Comment by jimcruse** [comment]
Builds now 10jul20 
gcc version 8.3.0 (Debian 8.3.0-6)

**Comment by sonam-packt** [comment]
@jimcruse okay great then ...I think your problem resolved.
