### ISSUE TITLE
Chapter09 auto_parallel does not compile

### ISSUE THREAD

**Issue by JungHong** [PacktPublishing/Cpp17-STL-Cookbook#2]
I tested the compilation of the programs in Chapter09 with 
    clang++-5.0 version 5.0.0 and
    g++-7 version 7.1.0

The program, auto_parallel.cpp does not compile with either of the above compilers:
1.  auto_parallel.cpp:5:10: fatal error: 'algorith' file not found
Then, with it commented out,  // #included <algorith> 
2. auto_parallel.cpp:6:10: fatal error: 'execution' file not found
3. I had to add  LDFLAGS = -lpthread to the Makefile so that the files would would produce execcutables.

If you could post how it was that auto_parallel.cpp compiled it would be appreciated. (What compiler did you use?  Were there required environmental variables?)

**Comment by tfc** [comment]
Hey JungHong,

i know this is frustrating, but this is not really implemented in the typical STL implementations, _yet_.
This means that you will have to wait a bit until it compiles with normal STL algorithms.

There are however existing implementations which you can use right now:

- https://github.com/STEllAR-GROUP/hpx
- https://parallelstl.codeplex.com/
- https://software.intel.com/en-us/get-started-with-pstl
- https://github.com/KhronosGroup/SyclParallelSTL
- ...

**Comment by JungHong** [comment]
Thanks for your reply.  I'll just do with the examples that do compile.  Two compilers g++ and clang++ is quit enough for me.  What I want to learn is C++, not more compilers, environments, etc.
