### ISSUE TITLE
Error during cartesian_product compilation by mingw 7.3.0 x64

### ISSUE THREAD

**Issue by GentleHedgehog** [PacktPublishing/Cpp17-STL-Cookbook#6]
I try to compile that code [https://github.com/PacktPublishing/Cpp17-STL-Cookbook/blob/master/Chapter04/cartesian_product.cpp] by mingw 7.3.0 x64, but I get an error: 
```
no matching function for call to 
'std::initializer_list<int>::initializer_list(<brace-enclosed initializer list>)' 
(void)std::initializer_list<int>{
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
((void)call_cart(f, xs, xs...), 0)...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     };
```
I noticed that I can fix the problem, if I change "xs..." to "1,2,3", for example

**Comment by sarvesh-packt** [comment]
Hi,

Please reopen if the issue still persists.

Regards
